name: ci

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Publish
      run: ./publish.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
